name: HW2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 pyflakes pyright pytest

      - name: Run AutoPep8
        run: |
          autopep8 --in-place --aggressive hw2_debugging.py
          autopep8 --in-place --aggressive rand.py

      - name: Run Pyflakes
        run: |
          pyflakes hw2_debugging.py
          pyflakes rand.py

      - name: Run Pyright
        run: |
          pyright hw2_debugging.py
          pyright rand.py

      - name: Run Pytest
        run: |
          pytest test_hw2_debugging.py  # Add this to run the test cases
