name: HW2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest
    name: AutoPep8 Formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install AutoPep8
        run: |
          python -m pip install autopep8
      - name: Run AutoPep8
        run: |
          autopep8 --in-place --aggressive hw2_debugging.py
          autopep8 --in-place --aggressive rand.py

  pyflakes:
    runs-on: ubuntu-latest
    name: Pyflakes Linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Pyflakes
        run: |
          python -m pip install pyflakes
      - name: Run Pyflakes
        run: |
          pyflakes hw2_debugging.py
          pyflakes rand.py

  pyright:
    runs-on: ubuntu-latest
    name: Pyright Type Checking
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Pyright
        run: |
          python -m pip install pyright
      - name: Run Pyright
        run: |
          pyright hw2_debugging.py
          pyright rand.py

  pylint:
    runs-on: ubuntu-latest
    name: Pylint Linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Pylint
        run: |
          python -m pip install pylint
      - name: Run Pylint
        run: |
          pylint hw2_debugging.py rand.py

  tests:
    runs-on: ubuntu-latest
    name: Pytest Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install pytest
      - name: Run Pytest
        run: |
          pytest test_hw2_debugging.py
